version: '3'
services:
  netdata:
    image: netdata/netdata
    hostname: Server-1
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/os-release:/host/etc/os-release:ro
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - ./netdatalib:/var/lib/netdata
      - ./netdatacache:/var/cache/netdata
    restart: always
